const images = {
   edit: require('./edit.svg').default,
   move: require('./move.svg').default,
   iconBoard: require('./iconBoard.svg').default,
   deleteIcon: require('./delete.svg').default,
   coppy: require('./coppy.svg').default,
   add: require('./add.svg').default,
   menu: require('./menu.svg').default,
   manage: require('./manage.svg').default,
   change: require('./change.svg').default,
   duplicate: require('./duplicate.svg').default,
   convert: require('./convert.svg').default,
   archive: require('./archive.svg').default,
   export: require('./export.svg').default,
   deleteTask: require('./deleteTask.svg').default,
   moveTo: require('./moveTo.svg').default,
   close: require('./close.svg').default,
   color: require('./color.svg').default,
   burger: require('./burger.svg').default,
   flower: require('./flower.svg').default,
   notification: require('./notification.svg').default,
   inbox: require('./inbox.svg').default,
   invite: require('./invite.svg').default,
   app: require('./app.svg').default,
   search: require('./search.svg').default,
   help: require('./help.svg').default,
   info: require('./info.svg').default,
   heart: require('./heart.svg').default,
   card: require('./card.svg').default,
   home: require('./home.svg').default,
   work: require('./work.svg').default,
   filter: require('./filter.svg').default
};

export default images;
